# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc663a675ce54686bcfc88b665b8c51f2d8fcaf7e5525a144dfb3b528ceed9afbbc1d920ebac4c54161631278bfc3cde0f7bfe10276a0e4621f02e2a4782e4ac

test:
  secret_key_base: c9a4a629694e155d8863d4023c238d866dc2a7aa4bcf3d98cb30202649b8fb0d78bc6e7ea772a444e6a74c7459f327be5e9ea8cbfd2d53ee644ec5302f761a2f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
